<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\InspectionController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CashierController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ReceptionController;

Route::get('/', function(){return auth()->check() ? redirect()->route('dashboard') : redirect()->route('login');});
Route::middleware('guest')->group(function(){
 Route::get('/login',[AuthController::class,'showLogin'])->name('login');
 Route::post('/login',[AuthController::class,'login'])->name('login.perform');
});
Route::get('/logout',[AuthController::class,'logout'])->name('logout');
Route::middleware('auth')->group(function(){
 Route::get('/reception',[ReceptionController::class,'index'])->name('reception.index')->middleware('permission:view_jobs');
 Route::post('/reception/search',[ReceptionController::class,'search'])->name('reception.search')->middleware('permission:view_jobs');
 Route::post('/reception/job',[ReceptionController::class,'createJob'])->name('reception.create-job')->middleware('permission:create_jobs');
 Route::get('/reception/services',[ReceptionController::class,'getServices'])->name('reception.services')->middleware('permission:view_jobs');
 Route::get('/customers/list',[CustomerController::class,'list'])->name('customers.list')->middleware('permission:view_customers');
 Route::get('/dashboard',[DashboardController::class,'index'])->name('dashboard')->middleware('permission:view_dashboard');
 Route::resource('customers',CustomerController::class)->middleware('permission:view_customers');
 Route::resource('vehicles',VehicleController::class)->middleware('permission:view_vehicles');
 Route::post('/vehicles/{vehicle}/transfer-ownership',[VehicleController::class,'transferOwnership'])->name('vehicles.transfer_ownership')->middleware('permission:view_vehicles');
 Route::resource('appointments',AppointmentController::class)->middleware('permission:view_appointments');
 Route::get('/jobs/board',[JobController::class,'board'])->name('jobs.board')->middleware('permission:view_board_jobs');
 Route::resource('jobs',JobController::class)->middleware('permission:view_jobs');
 Route::get('/jobs/{job}/inspection',[InspectionController::class,'edit'])->name('jobs.inspection.edit')->middleware('permission:edit_inspection_jobs');
 Route::post('/jobs/{job}/inspection',[InspectionController::class,'update'])->name('jobs.inspection.update')->middleware('permission:edit_inspection_jobs');
 Route::post('/jobs/{job}/status',[JobController::class,'status'])->name('jobs.status')->middleware('permission:change_status_jobs');
 Route::post('/jobs/{job}/additional-work',[JobController::class,'additionalWork'])->name('jobs.additional-work')->middleware('permission:request_additional_work_jobs');
 Route::post('/jobs/{job}/approve',[JobController::class,'approve'])->name('jobs.approve')->middleware('permission:approve_jobs');
 Route::post('/jobs/{job}/consume-part',[JobController::class,'consumePart'])->name('jobs.consume-part')->middleware('permission:consume_parts_jobs');
 Route::resource('inventory',InventoryController::class)->except(['show'])->parameters(['inventory'=>'product'])->middleware('permission:view_inventory');
 Route::post('/inventory/{product}/adjust',[InventoryController::class,'adjust'])->name('inventory.adjust')->middleware('permission:adjust_stock_inventory');
 Route::resource('categories',CategoryController::class)->middleware('permission:view_inventory');
 Route::resource('invoices',InvoiceController::class)->only(['index','show'])->middleware('permission:view_invoices');
 Route::post('/invoices/{invoice}/pay',[InvoiceController::class,'pay'])->name('invoices.pay')->middleware('permission:pay_invoices');
 Route::get('/invoices/{invoice}/print/{format?}',[InvoiceController::class,'printInvoice'])->name('invoices.print')->middleware('permission:print_invoices')->where('format','a4|thermal');
 Route::get('/cashier',[CashierController::class,'index'])->name('cashier.index')->middleware('permission:view_invoices');
 Route::get('/cashier/search',[CashierController::class,'search'])->name('cashier.search')->middleware('permission:view_invoices');
 Route::get('/cashier/payment/{job}',[CashierController::class,'payment'])->name('cashier.payment')->middleware('permission:pay_invoices');
 Route::post('/cashier/payment/{job}',[CashierController::class,'processPayment'])->name('cashier.process-payment')->middleware('permission:pay_invoices');
 Route::get('/cashier/print-options/{job}',[CashierController::class,'printOptions'])->name('cashier.print-options')->middleware('permission:print_invoices');
 Route::get('/reports',[ReportController::class,'index'])->name('reports')->middleware('permission:view_reports');
 Route::get('/settings/billing',[SettingsController::class,'index'])->name('settings.billing')->middleware('permission:view_settings');
 Route::post('/settings/billing',[SettingsController::class,'updateBilling'])->name('settings.billing.update')->middleware('permission:edit_billing_settings');
 Route::resource('users',UserController::class)->middleware('permission:view_users');
});
